- name: mongodb sever installation and config
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodb repo file into mongodb server
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo
  - name: install mongodb in the mongodb server
    ansible.builtin.command: dnf install mongodb-org -y 
    



